added page 22
droy312/hacktoberfest_2022_flutter_opensource_project pull request #30
Opened 2022-10-14 13:35 UTC by EvilShadow1518

added page 22 and created its button

2022-10-14 14:50 UTC, droy312 requested changes

2022-10-14 14:50 UTC, droy312 commented on lib/pages/page_22.dart
> +class Page22 extends StatelessWidget {
It will be Page23

2022-10-14 14:50 UTC, droy312 commented on lib/home_page.dart
> +import 'pages/page_22.dart';
page_23.dart

2022-10-14 14:50 UTC, droy312 commented on lib/home_page.dart
> +          PageButton(pageNumber: 22, page: Page22()),
PageButton(pageNumber: 23, page: Page23()),

2022-10-15 10:06 UTC, EvilShadow1518 commented on lib/pages/page_22.dart
> +class Page22 extends StatelessWidget {
ok

2022-10-15 10:08 UTC, closed without merging